"""
Configuration package initialization.
"""
from config.settings import (
    ROOT_DIR,
    LATEX_DIR,
    OUTPUT_DIR,
    PAPERWORK_DIR,
    TEMPLATES_DIR,
    APP_LOGS_DIR,
    WORK_LOGS_DIR,
    REPORT_TYPE,
    COVER_LETTER_TEX,
    MAIN_REPORT_TEX,
    COVER_LETTER_PDF,
    MAIN_REPORT_PDF,
    SUBMISSION_COVER_LETTER_PDF,
    SUBMISSION_REPORT_PDF,
    SUBMISSION_REPORT_DOCX,
    SUBMISSION_WORKLOGS_XLSX,
    SUBMISSION_WORKLOGS_PDF,
)

__all__ = [
    "ROOT_DIR",
    "LATEX_DIR",
    "OUTPUT_DIR",
    "PAPERWORK_DIR",
    "TEMPLATES_DIR",
    "APP_LOGS_DIR",
    "WORK_LOGS_DIR",
    "REPORT_TYPE",
    "COVER_LETTER_TEX",
    "MAIN_REPORT_TEX",
    "COVER_LETTER_PDF",
    "MAIN_REPORT_PDF",
    "SUBMISSION_COVER_LETTER_PDF",
    "SUBMISSION_REPORT_PDF",
    "SUBMISSION_REPORT_DOCX",
    "SUBMISSION_WORKLOGS_XLSX",
    "SUBMISSION_WORKLOGS_PDF",
]
